import decodeRanges from '../../decode-ranges.mjs';

export default decodeRanges('wW-AAABABAIaDFnKgqIBDACXDAIACAGOAYEAxevA4NsMAAJAMAEAAABABAJwyvFBAAgrABCABWAhHHIgvSABEggDZEaglg3DTBguODACAcJIGIGg_fgkFLIg1JVBaEZGDLGhPhIg2gyMgyGFhJbIWHBjvgpCABBhNgnhHRDDglbTW4NgIjEBIgvhDGADJDB');
