import decodeRanges from '../../decode-ranges.mjs';

export default decodeRanges('gwJwYlJiFJjFJmbJh1Jh1Jh1Jh1Jh1Jh1Jh1Jh1Jh1JhfJh1JhFJkVJhFJwdFJglJkrJh_JilJFJi1JhVJiFJFJ4InFJqlJglJjFJVJhVJmVJ1MVJwWFJwiFJFJsbJh_Jg7JiPJkVJlVJh1Jl1JhlJFThLJmlJhlJqVJhVJj1JhFJg1JllJ0HVJwklJhVJiFJoVJ191JwrTgxwk_JmlJn1Jj2JtUJxKVJ');
