import decodeRanges from '../../decode-ranges.mjs';

export default decodeRanges('wYiDAAAAEDUAgnCACPRglABIAAAABBAAXBfADEDAIAAAAABAcAKCOBDAABCBjFAEBAAJAACNAABESKAaCAABBFA4QIKAAAABCEJACABAJAiQAACCABAABAAWDl0AmeAhvAfAeBg9CBBBADBEA');
