import decodeRanges from '../../decode-ranges.mjs';

export default decodeRanges('ghAcAwVIAiSCizAgqCj1Ag8AAACBkkBwbjBsVADBsEAjFBicBgsAEAk5BlhDihBJBBBcCi6BhABu7BICwyuCkxAMAVBKBmfA3T7AkNBjiACAl9BhVBheAiXBiSCiPBj4A1IlABBg-BioAcAhAAwrzBwT8EgrDi8Bh0Dh-CiABFAPBhXBABhrAkpBh0Bl0BEOhoBj4CoEAAAj6BhWBmjBqzBhJB0soBiEAhABKAooBknA04FAx3nA');
