import decodeRanges from '../../decode-ranges.mjs';

export default decodeRanges('wYIABAAAMgvghCAhkOBGBJTABAdchYKAitKEfPgp4PKFhyPlqRg_Bg1gnMhyEAiGw4CgjmdFABNVhAVKI4N0WhDhLg8jBDAaABAABAAJADAAAAFADAAAAAACABAABAAAAAAAAAABAABDAGADADAAAJAQECAEAQ');
