import decodeRanges from '../../decode-ranges.mjs';

export default decodeRanges('grAPCg8AAAgsADAgkAeAr9AoOCxo6AMAgmCMCiKAgmEFAhDEEBDABABAGAeBBAAAekLfBhZAdYgnFnUAIAg1HhuAlPEBeJPj_iCVg-DfBkBgvUBF4M_bAs3AACijAPCg8AAAiCAFDw2gB4MFMCPNwfCAYAeAYAeAYAeAYAeAYAs7cxPSBwndI');
