import decodeRanges from '../../decode-ranges.mjs';

export default decodeRanges('ghALAPAwVIAiSCizAgqCj1Ag8AAACBkkBwbjBsVADBsEAjFBicBgsAEAk5BlhDihBJBBBcCi6BhABujAWBICwyuCkxAMAVBKBmfA3T7AkNBjiACAl9BhVBheAiXBiSCiPBj4A1IlABBg6ACBioALAPAhAAwrzBwT8EgrDi8Bh0Dh-CiABFAPBhXBABhrAkpBh0Bl0BEOhoBj4CoEAAAj6BhWBmjBqzBhJB0soBiEAhABKAooBknA04FAx3nA');
